name: "Music Light Sync"
version: "1.0"
slug: "music_light_sync"
description: "Sync your lights with music"
startup: "application"
boot: "auto"
homeassistant: "2023.0.0"
arch:
  - amd64
  - aarch64
  - armv7
options:
  lights: []
schema:
  lights:
    - str
